(() => {
  "use strict";

  const firebaseConfig = {
    apiKey: "AIzaSyBxVrLZ00yG5cEjxL2gyDXKaudDyPNvZM",
    authDomain: "predictstor.firebaseapp.com",
    projectId: "predictstor",
    storageBucket: "predictstor.firebasestorage.app",
    messagingSenderId: "984193094318",
    appId: "1:984193094318:web:5c5614bf83a431b98f133f",
    measurementId: "G-L254S3YZ5D"
  };

  const CROPS = [
    "Onion", "Potato", "Tomato", "Wheat", "Cotton", "Soybean", "Groundnut", "Chilli", "Brinjal", "Okra",
    "Cabbage", "Cauliflower", "Garlic", "Turmeric", "Banana", "Sugarcane", "Chickpea", "Pigeonpea", "Blackgram", "Greengram",
    "Mustard", "Sesame", "Sunflower", "Sorghum", "Pearl Millet", "Finger Millet", "Tapioca", "Mango", "Guava", "Pomegranate",
    "Grapes", "Papaya", "Watermelon", "Cucumber", "Capsicum", "Coriander", "Ginger"
  ];

  const makeRule = (temp, humidity, soil, stage, diseaseCue, pestCue, nutrientCue, action) => ({ temp, humidity, soil, stage, diseaseCue, pestCue, nutrientCue, action });
  const CROP_RULES = {
    Onion: makeRule([18, 30], [50, 70], [35, 55], "bulb formation", "High humidity with leaf wetness can increase foliar disease pressure.", "Check leaf bases and young leaves for thrips activity.", "Check nitrogen and sulphur plan if leaves are pale or growth is weak.", "Check soil moisture before irrigation and inspect lower leaves after humid weather."),
    Potato: makeRule([15, 25], [60, 80], [45, 70], "tuber initiation", "Cool, wet foliage can raise late-blight monitoring priority.", "Scout leaf undersides and field edges for aphids and defoliators.", "Use a soil or leaf test before changing nutrient inputs.", "Keep moisture even around tuber initiation and avoid prolonged saturation."),
    Tomato: makeRule([18, 30], [60, 75], [45, 70], "flowering and fruit set", "Humidity and long leaf-wetness periods warrant disease scouting.", "Inspect new growth and fruit clusters for whitefly, thrips, or mites.", "Confirm calcium and potassium decisions with crop stage and soil test.", "Inspect the canopy early and irrigate at the root zone rather than wetting leaves."),
    Wheat: makeRule([12, 25], [45, 70], [40, 65], "heading", "Humidity around the canopy should trigger disease scouting, not a diagnosis.", "Walk the field for aphids and caterpillar feeding signs.", "Use a soil test before top-dressing nitrogen.", "Monitor moisture through heading and avoid unnecessary irrigation before rain."),
    Cotton: makeRule([21, 32], [45, 70], [40, 65], "square and boll development", "Wet canopy periods can increase fungal disease watch priority.", "Scout the terminal and squares for sucking pests and boll damage.", "Review nitrogen and potassium against crop stage and soil test.", "Check soil moisture at root depth and inspect squares before acting."),
    Soybean: makeRule([20, 30], [55, 75], [45, 70], "pod development", "Dense, humid canopies need regular leaf and stem inspection.", "Check for defoliation and pod-feeding signs along field edges.", "Check nodulation and use a soil test before adding nutrients.", "Maintain even moisture during flowering and pod set; verify drainage after rain."),
    Groundnut: makeRule([22, 30], [50, 70], [40, 65], "pegging", "Leaf wetness and humidity warrant early leaf-spot scouting.", "Inspect the lower canopy and pegging zone for feeding damage.", "Confirm calcium and sulphur needs with soil and crop history.", "Prioritize moisture during pegging while preventing standing water."),
    Chilli: makeRule([20, 32], [55, 75], [40, 65], "flowering and fruiting", "Humidity and leaf wetness increase the need for regular disease scouting.", "Inspect new growth for thrips, mites, and aphids.", "Review nitrogen and micronutrients with soil or leaf evidence.", "Use root-zone irrigation and scout flowers and young fruits twice weekly."),
    Brinjal: makeRule([22, 32], [55, 75], [45, 70], "fruit development", "Warm, humid foliage needs disease observation after rainfall.", "Check shoot and fruit borer entry signs and leaf undersides.", "Use a soil test before changing nitrogen or potassium.", "Inspect fruiting shoots and avoid irregular wet-dry cycles."),
    Okra: makeRule([24, 32], [50, 70], [40, 65], "flowering and pod harvest", "Canopy wetness should trigger leaf and stem inspection.", "Scout tender shoots and leaf undersides for sucking pests.", "Check soil fertility and crop stage before supplementing nutrients.", "Harvest regularly, check moisture at root depth, and inspect new growth."),
    Cabbage: makeRule([15, 25], [60, 80], [45, 70], "head formation", "Cool, humid conditions warrant head and leaf disease scouting.", "Inspect leaf undersides for caterpillars and aphids.", "Use soil evidence before changing nitrogen or boron inputs.", "Keep moisture consistent and avoid water sitting around the root zone."),
    Cauliflower: makeRule([15, 25], [60, 80], [45, 70], "curd formation", "Humidity and wet foliage increase disease-monitoring priority.", "Scout inner leaves and growing points for caterpillar damage.", "Review boron and nitrogen decisions with local agronomy guidance.", "Monitor moisture around curd formation and ensure drainage after rainfall."),
    Garlic: makeRule([15, 28], [45, 65], [35, 55], "bulb enlargement", "Wet foliage and poor airflow warrant disease observation.", "Inspect leaf tips and young leaves for thrips.", "Check sulphur and nitrogen plan against soil and crop stage.", "Prefer measured root-zone irrigation and allow the surface to dry between events."),
    Turmeric: makeRule([20, 32], [60, 80], [50, 75], "rhizome bulking", "Persistent wetness requires rhizome and leaf disease scouting.", "Inspect leaf bases and new growth for pest activity.", "Use soil and leaf evidence before changing nutrient inputs.", "Maintain moisture during bulking but open drainage after heavy rain."),
    Banana: makeRule([20, 35], [60, 85], [55, 80], "bunch development", "High humidity and leaf wetness warrant leaf and pseudostem inspection.", "Check leaf axils and young leaves for sap-sucking pests.", "Review potassium and micronutrients with soil and leaf observations.", "Maintain root-zone moisture and check drainage after storms."),
    Sugarcane: makeRule([20, 35], [55, 80], [50, 75], "grand growth", "Dense, wet foliage should be inspected for disease spread.", "Walk borders and lower leaves for early pest signs.", "Base nitrogen and potassium adjustments on soil and crop history.", "Check moisture at root depth and inspect low areas for waterlogging."),
    Chickpea: makeRule([15, 28], [40, 65], [35, 55], "pod filling", "Cool, humid periods warrant foliar disease scouting.", "Inspect flowers and pods for pod borer activity.", "Check nodulation and soil test results before adding nitrogen.", "Avoid over-irrigation near maturity and inspect pods during field walks."),
    Pigeonpea: makeRule([20, 32], [45, 70], [40, 65], "flowering and pod set", "Canopy humidity should guide regular disease observation.", "Scout flowers and pods for pod borer and sucking pest signs.", "Use soil evidence before adding nutrients.", "Maintain moisture at flowering while checking field drainage."),
    Blackgram: makeRule([22, 32], [45, 70], [35, 60], "flowering", "Warm, humid canopies need disease scouting after rain.", "Inspect flowers and tender pods for sucking pests.", "Confirm nutrient stress through soil or leaf evidence.", "Avoid long wet periods and check soil moisture before irrigation."),
    Greengram: makeRule([22, 32], [45, 70], [35, 60], "flowering", "Leaf wetness warrants observation for foliar disease symptoms.", "Check flowers and pods for pest feeding signs.", "Review nodulation and soil evidence before adding nitrogen.", "Use shallow root-zone checks and protect drainage after rainfall."),
    Mustard: makeRule([10, 25], [45, 70], [35, 60], "flowering and siliqua", "Humid weather warrants scouting for foliar disease.", "Inspect flowering shoots for aphids and feeding damage.", "Use soil evidence before changing sulphur or nitrogen inputs.", "Avoid excess water and inspect plants during flowering."),
    Sesame: makeRule([22, 32], [45, 70], [30, 55], "capsule formation", "Wet foliage after rain needs disease observation.", "Check tender growth for sucking pests.", "Confirm nutrient stress with soil and crop history.", "Avoid excess irrigation and check lower field areas after rain."),
    Sunflower: makeRule([20, 32], [45, 70], [40, 65], "head formation", "Humid canopies should be inspected for foliar disease.", "Scout the head and lower canopy for pest feeding.", "Review boron and potassium with local guidance and soil evidence.", "Protect moisture through flowering and verify drainage after rain."),
    Sorghum: makeRule([22, 34], [40, 70], [35, 60], "booting and grain fill", "Humidity and leaf wetness warrant leaf and panicle inspection.", "Scout whorl and panicle for pest damage.", "Use soil evidence before nutrient changes.", "Check moisture at booting and avoid waterlogging."),
    "Pearl Millet": makeRule([25, 35], [35, 65], [30, 55], "panicle emergence", "Wet periods should trigger leaf and panicle observation.", "Inspect whorl and panicle for pest feeding.", "Review soil fertility and crop stage before supplementing.", "Monitor moisture without saturating shallow roots."),
    "Finger Millet": makeRule([20, 30], [45, 70], [35, 60], "ear emergence", "Leaf wetness requires disease observation.", "Scout leaves and ear heads for pest signs.", "Confirm nutrient stress with soil or leaf evidence.", "Check moisture at tillering and keep drainage open."),
    Tapioca: makeRule([22, 32], [50, 75], [40, 65], "root bulking", "Persistent wetness warrants leaf and root-zone observation.", "Inspect young leaves and stems for pest activity.", "Review potassium and soil fertility before changes.", "Maintain moisture during bulking but prevent standing water."),
    Mango: makeRule([20, 35], [45, 75], [40, 65], "flowering and fruit set", "Humidity during flowering warrants blossom and leaf observation.", "Scout flushes and panicles for hoppers and other pest signs.", "Use soil and leaf evidence before nutrient applications.", "Monitor moisture during fruit set and inspect after storms."),
    Guava: makeRule([20, 35], [50, 80], [45, 70], "fruit development", "Wet canopies need disease and fruit-surface observation.", "Inspect new flushes and fruit for pest signs.", "Review nutrient changes with soil and leaf evidence.", "Maintain even root-zone moisture and clear drainage."),
    Pomegranate: makeRule([20, 35], [40, 70], [35, 60], "flowering and fruit development", "Humidity and rain events warrant fruit and leaf scouting.", "Inspect flowers, shoots, and fruit for pest activity.", "Check soil and leaf evidence before changing nutrients.", "Avoid sudden moisture swings and inspect fruit after rain."),
    Grapes: makeRule([18, 32], [45, 70], [40, 65], "berry development", "Canopy humidity and leaf wetness require disease scouting.", "Inspect clusters and new shoots for pest signs.", "Use soil or leaf analysis before nutrient changes.", "Keep canopy ventilated and check irrigation at root depth."),
    Papaya: makeRule([22, 35], [55, 80], [45, 70], "fruit development", "Wet foliage and humidity warrant leaf and fruit observation.", "Inspect leaf undersides and fruit surface for pest signs.", "Review potassium and micronutrients with evidence.", "Maintain moisture and open drainage after heavy rainfall."),
    Watermelon: makeRule([22, 35], [50, 75], [40, 65], "fruit sizing", "Humid vine canopies should be inspected after rainfall.", "Check vine tips, flowers, and fruit for pest activity.", "Use soil and crop-stage evidence before nutrient changes.", "Keep moisture even during fruit sizing and avoid saturation."),
    Cucumber: makeRule([20, 30], [60, 80], [45, 70], "flowering and fruiting", "High humidity and leaf wetness increase disease-monitoring priority.", "Inspect new leaves and flowers for aphids, mites, and whitefly.", "Confirm nutrient stress with soil or leaf evidence.", "Use root-zone irrigation and increase airflow around the canopy."),
    Capsicum: makeRule([18, 30], [55, 75], [45, 70], "flowering and fruit set", "Humidity requires disease scouting around leaves and fruit.", "Check flowers and new growth for thrips and mites.", "Review calcium and potassium decisions with soil evidence.", "Avoid wet foliage and keep moisture even during fruit set."),
    Coriander: makeRule([15, 28], [45, 70], [35, 55], "leaf development", "Humid foliage warrants leaf disease observation.", "Inspect tender leaves for aphid and mite signs.", "Use soil evidence before adding nutrients.", "Use light, measured irrigation and avoid prolonged leaf wetness."),
    Ginger: makeRule([20, 32], [60, 80], [50, 75], "rhizome bulking", "Persistent wetness requires rhizome and leaf disease scouting.", "Inspect leaf bases and new growth for pests.", "Review soil fertility before nutrient changes.", "Maintain moisture during bulking and clear drainage after rainfall.")
  };

  const PAGE_TITLES = { dashboard: "Field overview", sensors: "Field sensor network", prediction: "Edge AI observation", alerts: "Alerts & actions", history: "Event history", traceability: "Recovery & harvest readiness", settings: "Settings & profile", help: "Help & about" };
  const STORAGE_PREFIX = "bhoominova_field_workspace_v2_";
  const SETTINGS_KEY = "bhoominova_settings_v2";
  const DEMO_TELEMETRY = { temperature: 29.2, humidity: 68, soilMoisture: 31, light: 72, rainfall: 18, source: "Illustrative demo input" };
  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => Array.from(document.querySelectorAll(selector));
  const text = (selector, value) => { const el = $(selector); if (el) el.textContent = value ?? ""; };
  const safeParse = (value, fallback) => { try { return value ? JSON.parse(value) : fallback; } catch (_) { return fallback; } };
  const nowIso = () => new Date().toISOString();
  const formatDate = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }); };
  const formatTime = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }); };
  const initials = (value) => String(value || "BN").split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase() || "BN";
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));

  let firebaseReady = false;
  let firebaseDb = null;
  let confirmationResult = null;
  let recaptchaVerifier = null;
  try {
    if (window.firebase) {
      if (!firebase.apps.length) firebase.initializeApp(firebaseConfig);
      firebaseReady = Boolean(firebase.auth);
      firebaseDb = firebase.firestore ? firebase.firestore() : null;
    }
  } catch (error) { console.warn("Firebase unavailable; local mode remains available.", error); }

  const DEFAULT_EVENTS = [
    { id: "event-system", type: "system", title: "Field intelligence workspace opened", detail: "Local rule engine initialized. No live telemetry or vision diagnosis is connected.", timestamp: nowIso() },
    { id: "event-boundary", type: "system", title: "Integration boundary recorded", detail: "ESP-12E is treated as a telemetry node; camera analysis is reserved for a separate edge device or future service.", timestamp: new Date(Date.now() - 3600000).toISOString() }
  ];
  const EMPTY_WORKSPACE = () => ({ profile: null, pairing: null, observations: [], alerts: [], events: [], traceEvents: [], telemetry: { ...DEMO_TELEMETRY }, settings: safeParse(localStorage.getItem(SETTINGS_KEY), { tempThreshold: 32, humidityThreshold: 75, localNotifications: true }) });
  const state = { session: null, workspace: EMPTY_WORKSPACE(), alertFilter: "open", historyFilter: "all" };

  function demoProfile() { return { name: "Demo Farmer", phone: "+91 98765 43210", farmerId: "BN-DEMO-001", farmName: "Shakti Farm", fieldName: "North field", crop: "Onion", location: "Nashik", district: "Nashik", state: "Maharashtra", coordinates: "20.0059, 73.7897", cultivation: "Kharif · drip irrigation", stage: "bulb formation", savedAt: nowIso() }; }
  function workspaceKey() { return state.session?.mode === "firebase" && state.session.uid ? state.session.uid : "demo"; }
  function storageKey() { return `${STORAGE_PREFIX}${workspaceKey()}`; }
  function saveWorkspace() { try { localStorage.setItem(storageKey(), JSON.stringify(state.workspace)); } catch (error) { console.warn("Local workspace could not be saved", error); } }
  function loadWorkspace() {
    const saved = safeParse(localStorage.getItem(storageKey()), null);
    state.workspace = saved ? { ...EMPTY_WORKSPACE(), ...saved, telemetry: { ...DEMO_TELEMETRY, ...(saved.telemetry || {}) }, settings: { ...EMPTY_WORKSPACE().settings, ...(saved.settings || {}) } } : EMPTY_WORKSPACE();
    if (!saved && state.session?.mode === "demo") { state.workspace.profile = demoProfile(); state.workspace.events = DEFAULT_EVENTS.map((item) => ({ ...item })); saveWorkspace(); }
  }
  function addEvent(type, title, detail) { state.workspace.events.unshift({ id: `event-${Date.now()}-${Math.random().toString(16).slice(2)}`, type, title, detail, timestamp: nowIso() }); saveWorkspace(); }
  function toast(message) { const el = $("#toast"); if (!el) return; el.textContent = message; el.classList.add("show"); window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => el.classList.remove("show"), 3000); }
  function openModal(id) { const el = $(`#${id}`); if (el) { el.classList.remove("hidden"); document.body.style.overflow = "hidden"; } }
  function closeModal(id) { const el = $(`#${id}`); if (el) { el.classList.add("hidden"); document.body.style.overflow = ""; } }
  function closeAllOverlays() { closeModal("loginModal"); closeModal("profileModal"); $("#profilePopover")?.classList.add("hidden"); document.body.style.overflow = ""; }
  function openLogin() { closeAllOverlays(); text("#loginMessage", ""); $("#otpSection")?.classList.add("hidden"); $("#phoneLoginForm")?.classList.remove("hidden"); openModal("loginModal"); }
  function openProfileForm() {
    if (!state.session) { openLogin(); return; }
    closeAllOverlays(); const profile = state.workspace.profile || {};
    ["profileName", "profileFarmerId", "profileFarmName", "profileFieldName", "profileLocation", "profileDistrict", "profileState", "profileCoordinates", "profileCultivation", "profileStage"].forEach((id) => { const el = $(`#${id}`); if (el) el.value = profile[id.replace("profile", "").replace(/^./, (char) => char.toLowerCase())] || ""; });
    const phone = $("#profilePhone"); if (phone) phone.value = profile.phone || state.session.phone || ""; const crop = $("#profileCrop"); if (crop) crop.value = profile.crop || ""; text("#profileFormMessage", ""); openModal("profileModal");
  }
  function setAvatar(selector, value) { const el = $(selector); if (el) el.textContent = initials(value); }
  function renderAuth() {
    const profile = state.workspace.profile; const loggedIn = Boolean(state.session); const name = profile?.name || (loggedIn ? "Farmer workspace" : "Guest workspace"); const role = loggedIn ? (state.session.mode === "demo" ? "Demo farmer · local" : "Farmer · verified mobile") : "Login to begin";
    ["#topAvatar", "#sidebarAvatar", "#settingsAvatar", "#popoverAvatar"].forEach((selector) => setAvatar(selector, name));
    text("#topName", profile?.name || (loggedIn ? "Farmer" : "Guest")); text("#topRole", loggedIn ? role : "Not signed in"); text("#sidebarName", name); text("#sidebarRole", role); text("#popoverName", name); text("#popoverRole", role); text("#popoverPhone", profile?.phone || state.session?.phone || "Not signed in"); text("#popoverFarmerId", profile?.farmerId || "Pending setup"); text("#settingsName", name); text("#settingsRole", loggedIn ? role : "Farmer profile locked"); text("#settingsPhone", profile?.phone || state.session?.phone || "Not signed in"); text("#settingsFarmerId", profile?.farmerId || "—"); text("#settingsFarm", profile ? `${profile.farmName || "Farm"} · ${profile.fieldName || "Field"}` : "—"); text("#settingsLocation", profile ? [profile.location, profile.district, profile.state].filter(Boolean).join(", ") || "Not saved" : "—");
    const pill = $("#profileStatusPill"); if (pill) { pill.textContent = loggedIn ? (profile ? "Profile ready" : "Setup pending") : "Signed out"; pill.className = `pill ${loggedIn && profile ? "pill-green" : "pill-neutral"}`; }
    $("#popoverLoginBtn")?.classList.toggle("hidden", loggedIn); $("#popoverLogoutBtn")?.classList.toggle("hidden", !loggedIn); text("#authStripText", loggedIn ? (state.session.mode === "demo" ? "Local field workspace · data stays in this browser." : "Verified farmer workspace · profile data is scoped to this account.") : "This view is locked until a farmer signs in."); const stripButton = $("#authStripBtn"); if (stripButton) stripButton.textContent = loggedIn ? "Edit profile" : "Sign in"; text("#connectionLabel", "Offline ready"); text("#connectionSubtext", loggedIn ? "Local field workspace is available." : "Local workspace is available.");
  }
  function renderSelectOptions() {
    const dataList = $("#cropCatalog"); if (dataList) dataList.innerHTML = CROPS.map((crop) => `<option value="${escapeHtml(crop)}"></option>`).join("");
    const profile = state.workspace.profile; const fieldSelects = [$("#pairField"), $("#observationField")]; fieldSelects.forEach((select) => { if (!select) return; const current = select.value; select.innerHTML = `<option value="">Select field</option>${profile ? `<option value="${escapeHtml(profile.fieldName || "Primary field")}">${escapeHtml(profile.fieldName || "Primary field")} · ${escapeHtml(profile.farmName || "Farm")}</option>` : ""}`; select.value = current || profile?.fieldName || ""; });
  }
  function getRule(crop) { return CROP_RULES[crop] || null; }
  function clamp(value, min, max) { return Math.min(max, Math.max(min, value)); }
  function riskState(label, reason, action, score) { return { label, reason, action, score }; }
  function buildAssessment(profile) {
    if (!profile?.crop) return null;
    const rule = getRule(profile.crop); if (!rule) return null; const t = state.workspace.telemetry || DEMO_TELEMETRY; const note = String((state.workspace.observations || [])[0]?.notes || "").toLowerCase();
    const heatScore = t.temperature > rule.temp[1] + 5 ? 2 : t.temperature > rule.temp[1] ? 1 : 0;
    const droughtScore = t.soilMoisture < rule.soil[0] - 8 ? 2 : t.soilMoisture < rule.soil[0] ? 1 : 0;
    const floodScore = t.rainfall > 50 || t.soilMoisture > 85 ? 2 : t.rainfall > 30 || t.soilMoisture > 75 ? 1 : 0;
    const diseaseScore = t.humidity > rule.humidity[1] && t.temperature >= rule.temp[0] - 2 ? 1 : 0;
    const pestScore = t.temperature > rule.temp[1] && t.humidity < rule.humidity[0] ? 1 : 0;
    const nutrientScore = /(yellow|pale|stunt|chlor|deficien|weak growth)/.test(note) ? 1 : 0;
    const irrigationScore = t.soilMoisture < rule.soil[0] ? 2 : t.soilMoisture < rule.soil[0] + 8 ? 1 : 0;
    const stateFor = (score, high, watch) => score >= high ? riskState("High", "The current illustrative input is outside the crop reference band.", "Verify locally before acting.", score) : score >= watch ? riskState("Watch", "The current illustrative input is close to a crop-specific watch condition.", "Inspect the field and re-check the input.", score) : riskState("Low", "No elevated condition is indicated by the illustrative input.", "Continue scheduled scouting.", score);
    const disease = stateFor(diseaseScore, 2, 1); disease.reason = diseaseScore ? rule.diseaseCue : "Humidity and temperature are inside the current crop reference band."; disease.action = rule.action;
    const pest = stateFor(pestScore, 2, 1); pest.reason = pestScore ? rule.pestCue : "No temperature/humidity combination is raising a pest watch in this local rule set."; pest.action = rule.pestCue;
    const nutrient = stateFor(nutrientScore, 2, 1); nutrient.reason = nutrientScore ? "The latest farmer note contains a possible stress cue; this is not a nutrient diagnosis." : "No farmer note is currently flagging visible nutrient stress."; nutrient.action = rule.nutrientCue;
    const irrigation = stateFor(irrigationScore, 2, 1); irrigation.reason = irrigationScore ? `Soil moisture is ${t.soilMoisture}% against the ${rule.soil[0]}–${rule.soil[1]}% crop reference band.` : `Soil moisture is ${t.soilMoisture}% within the ${rule.soil[0]}–${rule.soil[1]}% crop reference band.`; irrigation.action = rule.action;
    const heat = stateFor(heatScore, 2, 1); heat.reason = `Temperature is ${t.temperature}°C against the ${rule.temp[0]}–${rule.temp[1]}°C crop reference band.`; heat.action = "Provide shade or heat protection only after local field verification.";
    const drought = stateFor(droughtScore, 2, 1); drought.reason = droughtScore ? "Soil moisture is below the crop-specific lower reference band." : "Soil moisture does not indicate drought stress in this illustrative input."; drought.action = "Check soil at root depth and confirm irrigation need before applying water.";
    const flood = stateFor(floodScore, 2, 1); flood.reason = floodScore ? "Rainfall or soil moisture is high enough to warrant drainage inspection." : "No waterlogging watch is indicated by the illustrative rainfall and soil moisture input."; flood.action = "Inspect low points and field drains after heavy rainfall.";
    const risks = { disease, pest, nutrient, irrigation, heat, drought, flood };
    const priority = [ [irrigation, "Check soil moisture before irrigation", rule.action, "prediction"], [flood, "Inspect field drainage after heavy rainfall", flood.action, "sensors"], [disease, "Inspect lower leaves for disease symptoms", rule.diseaseCue, "prediction"], [pest, "Scout the crop for pest activity", rule.pestCue, "prediction"], [nutrient, "Record a farmer observation before changing inputs", rule.nutrientCue, "prediction"], [heat, "Review heat protection at the field edge", heat.action, "sensors"], [drought, "Verify root-zone moisture", drought.action, "sensors"] ];
    const next = priority.find(([item]) => item.label !== "Low") || [null, "Continue scheduled field scouting", rule.action, "prediction"];
    return { crop: profile.crop, rule, risks, telemetry: t, next: { title: next[1], reason: next[2], page: next[3] } };
  }
  function statusClass(label) { return label === "High" ? "risk-high" : label === "Watch" ? "risk-watch" : "risk-low"; }
  function riskCard(title, icon, item) { return `<article class="risk-card ${statusClass(item.label)}"><div class="risk-card-top"><span class="risk-icon">${icon}</span><span class="risk-label">${escapeHtml(item.label)}</span></div><strong>${escapeHtml(title)}</strong><p>${escapeHtml(item.reason)}</p><small>${escapeHtml(item.action)}</small></article>`; }
  function alertMini(item) { return `<div class="alert-item ${escapeHtml(item.level)}"><span class="alert-item-indicator"></span><div><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.reason || item.desc)}</p><small>${escapeHtml(item.crop || "Crop")} · ${escapeHtml(item.field || "Field")} · ${escapeHtml(item.recommendedAction || "Inspect locally")}</small></div></div>`; }
  function assessmentAlerts(profile, assessment) { if (!profile || !assessment) return []; return Object.entries(assessment.risks).filter(([, item]) => item.label !== "Low").map(([type, item], index) => ({ id: `risk-${type}`, level: item.label === "High" ? "danger" : "warning", title: `${type[0].toUpperCase()}${type.slice(1)} risk · ${item.label}`, reason: item.reason, recommendedAction: item.action, desc: item.reason, time: "Illustrative input · review locally", field: profile.fieldName, crop: profile.crop, riskType: type, severity: item.label, status: "open", demo: true, createdAt: nowIso(), order: index })); }
  function renderDashboard() {
    const profile = state.workspace.profile; const assessment = buildAssessment(profile); const openAlerts = assessmentAlerts(profile, assessment);
    text("#welcomeName", profile?.name ? profile.name.split(" ")[0] : "farmer"); text("#welcomeSummary", profile ? `${profile.fieldName || "Your field"} · ${profile.crop || "Crop not selected"} · ${profile.location || "Location not saved"}. Guidance is crop-specific and not a diagnosis.` : "Sign in to open your private field workspace. Demo values are never presented as live telemetry."); text("#statField", profile?.fieldName || "Not configured"); text("#statLocation", profile ? [profile.location, profile.district].filter(Boolean).join(" · ") || "Location not saved" : "Location not saved"); text("#statHealth", assessment ? (Object.values(assessment.risks).some((item) => item.label === "High") ? "Review" : "Monitor") : "—"); text("#statHealthFoot", assessment ? "Rule-based indicator · not diagnosis" : "No assessment"); text("#statAlerts", openAlerts.length); text("#statAlertsFoot", openAlerts.length ? "Review recommended actions" : "No elevated demo signal"); text("#statSensor", state.workspace.pairing ? "Registered" : "Ready"); text("#statSensorFoot", state.workspace.pairing ? "Gateway not verified" : "No live connection"); text("#fieldPanelTitle", profile?.fieldName || "Your primary field"); text("#fieldPanelBadge", profile ? "Crop rules active" : "Not configured"); text("#fieldCrop", profile ? `${profile.crop || "Crop not selected"} · ${profile.farmName || "Farm"}` : "Search for a crop to begin"); text("#fieldMeta", profile ? `${profile.location || "Location not saved"} · ${profile.state || "State not saved"} · ${profile.stage || assessment?.rule.stage || "Stage to be added"}` : "Field, crop, and location details will appear here."); text("#fieldDistrict", profile?.district || "—"); text("#fieldCultivation", profile?.cultivation || "—"); text("#fieldUpdated", profile?.savedAt ? formatDate(profile.savedAt) : "—"); text("#healthRingValue", assessment ? (Object.values(assessment.risks).filter((item) => item.label === "Low").length * 14 + 2) : "—");
    const container = $("#dashboardAlerts"); if (container) container.innerHTML = openAlerts.length ? openAlerts.slice(0, 3).map(alertMini).join("") : `<div class="empty-state"><strong>No elevated illustrative signals</strong><span>Live alerts appear only after a verified telemetry or vision service is connected.</span></div>`;
    const matrix = $("#riskMatrix"); if (matrix) matrix.innerHTML = assessment ? [riskCard("Disease risk", "⌁", assessment.risks.disease), riskCard("Pest risk", "◌", assessment.risks.pest), riskCard("Nutrient stress", "◇", assessment.risks.nutrient), riskCard("Irrigation need", "≈", assessment.risks.irrigation), riskCard("Heat stress", "☼", assessment.risks.heat), riskCard("Drought risk", "∿", assessment.risks.drought), riskCard("Flood / waterlogging", "▱", assessment.risks.flood)].join("") : `<div class="empty-state"><strong>Set up a field and crop</strong><span>The crop-aware risk picture will use crop, location, farmer notes, and sensor observations.</span></div>`;
    text("#nextBestAction", assessment?.next.title || "Set up a field first"); text("#nextBestActionReason", assessment?.next.reason || "Choose a farmer profile, field, crop, and location to unlock crop-specific guidance."); const nextButton = $("#nextBestActionBtn"); if (nextButton) { nextButton.dataset.page = assessment?.next.page || "settings"; nextButton.textContent = assessment ? "Review action" : "Set up field"; }
    text("#navAlertBadge", openAlerts.length); text("#topAlertBadge", openAlerts.length); $("#topAlertBadge")?.classList.toggle("hidden", !openAlerts.length);
  }
  function sensorCard(title, glyph, value, foot) { return `<article class="sensor-card"><div class="sensor-card-head"><span><i class="sensor-glyph">${glyph}</i>${title}</span><span class="status-dot offline"></span></div><strong class="sensor-card-value">${value}</strong><div class="sensor-card-footer"><span>${foot}</span><span class="pill pill-amber">Demo input</span></div></article>`; }
  function renderSensors() { const t = state.workspace.telemetry || DEMO_TELEMETRY; const cards = $("#sensorCards"); if (cards) cards.innerHTML = [sensorCard("Temperature", "°", `${t.temperature}°C`, "Illustrative value"), sensorCard("Humidity", "%", `${t.humidity}%`, "Illustrative value"), sensorCard("Soil moisture", "≈", `${t.soilMoisture}%`, "Illustrative value"), sensorCard("Light", "☼", `${t.light}%`, "Illustrative value")].join(""); const result = $("#pairingResult"); if (result) result.innerHTML = state.workspace.pairing ? `<span class="status-dot offline"></span><div><strong>${escapeHtml(state.workspace.pairing.deviceId)} · registered locally</strong><p>Field: ${escapeHtml(state.workspace.pairing.field)} · Hardware connection not verified.</p></div>` : `<span class="status-dot offline"></span><div><strong>No verified node connection</strong><p>Register an ESP-12E ID when the field kit is available.</p></div>`; const deviceInput = $("#deviceId"); if (deviceInput && state.workspace.pairing && !deviceInput.value) deviceInput.value = state.workspace.pairing.deviceId; }
  function renderIntelligence() { const profile = state.workspace.profile; const assessment = buildAssessment(profile); const rule = assessment?.rule; text("#intelligenceCrop", profile?.crop || "Search for a crop"); text("#intelligenceLocation", profile ? [profile.fieldName, profile.location, profile.stage || rule?.stage].filter(Boolean).join(" · ") : "Set up a field to see the right profile."); text("#riskScore", assessment ? `${Object.values(assessment.risks).filter((item) => item.label === "Low").length}/7` : "—"); text("#guidanceHeadline", profile ? `${profile.crop} optimization layer` : "No crop profile yet"); text("#guidanceBody", profile ? `Reference bands and crop-specific actions are selected for ${profile.crop}. This local engine does not diagnose disease, estimate yield, or browse live sources.` : "Choose a crop in the farmer profile to load the extendable rule set."); const pill = $("#riskPill"); if (pill) { pill.textContent = profile ? "Crop rules active" : "No assessment"; pill.className = `pill ${profile ? "pill-green" : "pill-neutral"}`; } const rec = $("#recommendationDetails"); if (rec) rec.innerHTML = rule ? `<div class="recommendation-row"><span>°</span><div><strong>Temperature reference</strong><small>${rule.temp[0]}–${rule.temp[1]}°C · location and stage should be verified locally</small></div></div><div class="recommendation-row"><span>%</span><div><strong>Humidity reference</strong><small>${rule.humidity[0]}–${rule.humidity[1]}% · watch canopy wetness, not just a single reading</small></div></div><div class="recommendation-row"><span>≈</span><div><strong>Soil moisture reference</strong><small>${rule.soil[0]}–${rule.soil[1]}% · check sensor calibration and root-zone depth</small></div></div><div class="recommendation-row"><span>↗</span><div><strong>Growth-stage lens</strong><small>${escapeHtml(rule.stage)} · ${escapeHtml(rule.action)}</small></div></div><div class="recommendation-row"><span>i</span><div><strong>Research-backed boundary</strong><small>Indicative rule scaffolding aligned to ICAR/TNAU/FAO-style agronomy references; confirm with local extension advice.</small></div></div>` : `<div class="empty-state"><strong>Choose a crop in Settings</strong><span>Crop-specific guidance will appear here.</span></div>`; }
  function renderAlerts() { const profile = state.workspace.profile; const assessment = buildAssessment(profile); const alerts = assessmentAlerts(profile, assessment); const open = alerts.filter((item) => item.status === "open"); text("#openAlertCount", open.length); text("#resolvedAlertCount", (state.workspace.alerts || []).filter((item) => item.status === "resolved").length); const list = $("#alertsList"); if (!list) return; const visible = state.alertFilter === "all" ? [...alerts, ...(state.workspace.alerts || []).filter((item) => item.status === "resolved")] : state.alertFilter === "resolved" ? (state.workspace.alerts || []).filter((item) => item.status === "resolved") : open; list.innerHTML = visible.length ? visible.map(alertRecord).join("") : `<div class="panel empty-state"><strong>${state.alertFilter === "resolved" ? "No resolved alerts yet" : "No open alerts"}</strong><span>Live alerts remain integration-ready and are never invented as diagnoses.</span></div>`; }
  function alertRecord(item) { const resolved = item.status === "resolved"; return `<article class="alert-record"><span class="alert-record-marker ${escapeHtml(item.level || "warning")}"></span><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.reason || item.desc)}</p><div class="alert-meta"><span>${escapeHtml(item.time || "Illustrative input")}</span><span>${escapeHtml(item.field || "Field not set")}</span><span>${escapeHtml(item.crop || "Crop not set")}</span><span>${escapeHtml(item.riskType || "field signal")}</span><span class="pill ${resolved ? "pill-green" : item.level === "danger" ? "pill-rose" : "pill-amber"}">${resolved ? "Resolved" : item.demo ? "Review locally" : "Open"}</span></div><small class="alert-action-line"><b>Recommended action:</b> ${escapeHtml(item.recommendedAction || "Inspect locally")}</small></div><div class="alert-actions"><small>${resolved ? `Resolved ${formatDate(item.resolvedAt)}` : "Action required"}</small>${resolved ? "" : `<button class="btn btn-secondary resolve-alert" data-alert-id="${escapeHtml(item.id)}" type="button">Mark reviewed</button>`}</div></article>`; }
  function renderHistory() { const events = state.workspace.events || []; const visible = state.historyFilter === "all" ? events : events.filter((item) => item.type === state.historyFilter); const list = $("#historyList"); if (!list) return; list.innerHTML = visible.length ? visible.map((event) => `<article class="history-item"><time>${formatTime(event.timestamp)}</time><div class="history-item-body"><strong>${escapeHtml(event.title)}</strong><p>${escapeHtml(event.detail)}</p><span class="history-item-tag">${escapeHtml(event.type)}</span></div></article>`).join("") : `<div class="empty-state"><strong>No events match this filter</strong><span>Actions and observations will appear here as you use the workspace.</span></div>`; }
  function renderTraceability() { const profile = state.workspace.profile; text("#traceabilityTitle", profile ? `${profile.fieldName || "Primary field"} · ${profile.crop || "Crop not selected"}` : "Set up a field to begin"); text("#traceabilitySubtitle", profile ? `${profile.farmName || "Farm"} · ${[profile.location, profile.district, profile.state].filter(Boolean).join(", ") || "Location not saved"}` : "Your farmer-owned recovery record will appear here."); const observationCount = state.workspace.observations?.length || 0; const steps = [{ title: "Field setup", detail: profile ? "Registered" : "Awaiting setup", done: Boolean(profile) }, { title: "Crop rules", detail: profile?.crop ? `${profile.crop} active` : "Awaiting crop", done: Boolean(profile?.crop) }, { title: "Observation", detail: observationCount ? `${observationCount} recorded` : "Ready for Edge AI", done: observationCount > 0 }, { title: "Farmer action", detail: state.workspace.events?.some((e) => e.type === "action") ? "Recorded" : "Ready to record", done: state.workspace.events?.some((e) => e.type === "action") }, { title: "Recovery", detail: "Guided record", done: false }, { title: "Harvest readiness", detail: "Requires field verification", done: false }]; const timeline = $("#traceabilityTimeline"); if (timeline) timeline.innerHTML = steps.map((step) => `<div class="trace-step ${step.done ? "" : "locked"}"><strong>${step.title}</strong><span>${step.detail}</span></div>`).join(""); }
  function renderSettings() { const settings = state.workspace.settings || {}; const temp = $("#tempThreshold"); const humidity = $("#humidityThreshold"); const notifications = $("#localNotifications"); if (temp) temp.value = settings.tempThreshold ?? 32; if (humidity) humidity.value = settings.humidityThreshold ?? 75; if (notifications) notifications.checked = settings.localNotifications !== false; }
  function renderAll() { renderAuth(); renderSelectOptions(); renderDashboard(); renderSensors(); renderIntelligence(); renderAlerts(); renderHistory(); renderTraceability(); renderSettings(); drawAllCharts(); }
  function drawChart(canvasId, dataSets, colors) { const canvas = $(`#${canvasId}`); if (!canvas || !canvas.offsetWidth) return; const width = canvas.offsetWidth; const height = Number(canvas.getAttribute("height")) || 220; const ratio = window.devicePixelRatio || 1; canvas.width = width * ratio; canvas.height = height * ratio; canvas.style.height = `${height}px`; const ctx = canvas.getContext("2d"); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); ctx.clearRect(0, 0, width, height); const pad = { top: 15, right: 12, bottom: 22, left: 22 }; ctx.strokeStyle = "#e8efea"; ctx.lineWidth = 1; for (let i = 0; i < 4; i += 1) { const y = pad.top + i * ((height - pad.top - pad.bottom) / 3); ctx.beginPath(); ctx.moveTo(pad.left, y); ctx.lineTo(width - pad.right, y); ctx.stroke(); } dataSets.forEach((values, setIndex) => { ctx.beginPath(); values.forEach((value, index) => { const x = pad.left + index * ((width - pad.left - pad.right) / Math.max(values.length - 1, 1)); const y = pad.top + (height - pad.top - pad.bottom) * (1 - clamp(value, 0, 100) / 100); if (index === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y); }); ctx.strokeStyle = colors[setIndex]; ctx.lineWidth = 2; ctx.stroke(); }); ctx.fillStyle = "#91a097"; ctx.font = "10px DM Sans"; ["-12h", "-8h", "-4h", "Now"].forEach((label, index, labels) => { const x = pad.left + index * ((width - pad.left - pad.right) / (labels.length - 1)); ctx.fillText(label, x - 10, height - 5); }); }
  function drawAllCharts() { const t = state.workspace.telemetry || DEMO_TELEMETRY; drawChart("dashboardChart", [[t.humidity - 5, t.humidity - 2, t.humidity, t.humidity - 1, t.humidity, t.humidity + 1, t.humidity], [t.temperature * 2 - 8, t.temperature * 2 - 6, t.temperature * 2 - 4, t.temperature * 2 - 3, t.temperature * 2 - 2, t.temperature * 2, t.temperature * 2]], ["#168255", "#5d96bc"]); drawChart("sensorChart", [[t.soilMoisture - 6, t.soilMoisture - 2, t.soilMoisture, t.soilMoisture + 2, t.soilMoisture + 1, t.soilMoisture], [t.temperature * 2 - 8, t.temperature * 2 - 5, t.temperature * 2 - 2, t.temperature * 2 - 3, t.temperature * 2, t.temperature * 2]], ["#168255", "#c69446"]); }
  function navigate(page) { const target = $(`#${page}`); if (!target) return; $$(".page").forEach((item) => item.classList.remove("active-page")); target.classList.add("active-page"); $$(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.page === page)); text("#pageTitle", PAGE_TITLES[page] || "Field overview"); $("#appShell")?.classList.remove("nav-open"); window.scrollTo({ top: 0, behavior: "smooth" }); window.setTimeout(drawAllCharts, 30); }
  async function saveProfile(profile) { state.workspace.profile = { ...(state.workspace.profile || {}), ...profile, savedAt: nowIso() }; state.workspace.alerts = []; saveWorkspace(); addEvent("system", "Farmer field profile saved", `${state.workspace.profile.name} updated the crop and field profile.`); if (state.session?.mode === "firebase" && firebaseDb && firebase.auth().currentUser) { try { await firebaseDb.collection("farmers").doc(firebase.auth().currentUser.uid).set({ ...state.workspace.profile, uid: firebase.auth().currentUser.uid, phone: firebase.auth().currentUser.phoneNumber || state.workspace.profile.phone, updatedAt: firebase.firestore.FieldValue.serverTimestamp() }, { merge: true }); toast("Profile saved to the browser and Firebase."); } catch (error) { console.warn("Firebase profile save failed", error); toast("Profile saved locally; Firebase sync is unavailable."); } } else toast("Field profile saved locally. Crop-specific guidance is active."); closeModal("profileModal"); renderAll(); }
  async function loadFirebaseProfile(user) { if (!firebaseDb) return null; try { const doc = await firebaseDb.collection("farmers").doc(user.uid).get(); return doc.exists ? { uid: user.uid, ...doc.data(), phone: user.phoneNumber || doc.data().phone } : null; } catch (error) { console.warn("Firebase profile load failed", error); return null; } }
  async function signOut() { try { if (state.session?.mode === "firebase" && firebaseReady) await firebase.auth().signOut(); } catch (error) { console.warn("Firebase sign out failed", error); } state.session = null; state.workspace = EMPTY_WORKSPACE(); closeAllOverlays(); navigate("dashboard"); renderAll(); toast("You have been logged out. Private farmer information is cleared from view."); }
  function bindEvents() {
    $$('[data-page]').forEach((button) => button.addEventListener("click", () => navigate(button.dataset.page)));
    $("#mobileMenuBtn")?.addEventListener("click", () => $("#appShell")?.classList.add("nav-open")); $("#mobileCloseNav")?.addEventListener("click", () => $("#appShell")?.classList.remove("nav-open")); $("#mobileBackdrop")?.addEventListener("click", () => $("#appShell")?.classList.remove("nav-open"));
    [$("#topProfileBtn"), $("#sidebarProfileBtn")].forEach((button) => button?.addEventListener("click", () => $("#profilePopover")?.classList.toggle("hidden")));
    $("#popoverLoginBtn")?.addEventListener("click", openLogin); $("#popoverLogoutBtn")?.addEventListener("click", signOut); $("#popoverEditBtn")?.addEventListener("click", () => { $("#profilePopover")?.classList.add("hidden"); state.session ? (state.workspace.profile ? navigate("settings") : openProfileForm()) : openLogin(); }); $("#topAlertBtn")?.addEventListener("click", () => navigate("alerts")); $("#authStripBtn")?.addEventListener("click", () => state.session ? openProfileForm() : openLogin()); $("#dashboardSetupBtn")?.addEventListener("click", () => state.session ? openProfileForm() : openLogin()); $("#editProfilePageBtn")?.addEventListener("click", openProfileForm); $("#settingsLogoutBtn")?.addEventListener("click", signOut);
    $$('[data-close-modal]').forEach((button) => button.addEventListener("click", () => closeModal(button.dataset.closeModal))); $$(".modal").forEach((modal) => modal.addEventListener("click", (event) => { if (event.target === modal) closeModal(modal.id); })); document.addEventListener("click", (event) => { const popover = $("#profilePopover"); if (popover && !popover.classList.contains("hidden") && !popover.contains(event.target) && !event.target.closest(".top-profile") && !event.target.closest(".sidebar-profile")) popover.classList.add("hidden"); });
    $("#demoLoginBtn")?.addEventListener("click", () => { state.session = { mode: "demo", phone: "+91 98765 43210" }; loadWorkspace(); closeModal("loginModal"); renderAll(); toast("Demo field workspace opened. Inputs remain locally labelled."); });
    $("#phoneLoginForm")?.addEventListener("submit", async (event) => { event.preventDefault(); const input = $("#phoneNumber"); const phone = input?.value.trim(); if (!/^\+\d{8,15}$/.test(phone || "")) { text("#loginMessage", "Enter a valid number with country code, such as +919876543210."); return; } if (!firebaseReady) { text("#loginMessage", "Phone authentication is not available in this browser. Use the demo workspace or connect Firebase Auth."); return; } try { if (!recaptchaVerifier) recaptchaVerifier = new firebase.auth.RecaptchaVerifier("recaptcha-container", { size: "invisible" }); confirmationResult = await firebase.auth().signInWithPhoneNumber(phone, recaptchaVerifier); $("#phoneLoginForm")?.classList.add("hidden"); $("#otpSection")?.classList.remove("hidden"); text("#loginMessage", "Verification code sent. Check your phone."); } catch (error) { console.error(error); text("#loginMessage", "Could not send a code. Check Firebase Auth configuration or use the demo workspace."); } });
    $("#verifyOtpBtn")?.addEventListener("click", async () => { const code = $("#otpCode")?.value.trim(); if (!confirmationResult || !/^\d{6}$/.test(code || "")) { text("#loginMessage", "Enter the 6-digit verification code."); return; } try { await confirmationResult.confirm(code); closeModal("loginModal"); } catch (error) { console.error(error); text("#loginMessage", "The verification code could not be confirmed."); } });
    $("#profileForm")?.addEventListener("submit", async (event) => { event.preventDefault(); const values = { name: $("#profileName")?.value.trim(), phone: $("#profilePhone")?.value.trim(), farmerId: $("#profileFarmerId")?.value.trim(), farmName: $("#profileFarmName")?.value.trim(), fieldName: $("#profileFieldName")?.value.trim(), crop: $("#profileCrop")?.value.trim(), location: $("#profileLocation")?.value.trim(), district: $("#profileDistrict")?.value.trim(), state: $("#profileState")?.value.trim(), coordinates: $("#profileCoordinates")?.value.trim(), cultivation: $("#profileCultivation")?.value.trim(), stage: $("#profileStage")?.value.trim() }; if (!values.name || !values.farmerId || !values.fieldName || !CROP_RULES[values.crop]) { text("#profileFormMessage", "Enter name, Farmer ID, field name, and one crop from the searchable catalog."); return; } await saveProfile(values); });
    $("#pairingForm")?.addEventListener("submit", (event) => { event.preventDefault(); const field = $("#pairField")?.value; const deviceId = $("#deviceId")?.value.trim(); if (!field || !deviceId) { toast("Select a field and enter the ESP-12E device ID."); return; } state.workspace.pairing = { field, deviceId, registeredAt: nowIso(), connected: false }; addEvent("system", "Telemetry node registered", `${deviceId} was registered locally for ${field}; live connection is not verified.`); saveWorkspace(); renderAll(); toast("ESP-12E registration saved locally. Hardware remains disconnected until verified."); });
    $("#observationImage")?.addEventListener("change", (event) => { const file = event.target.files?.[0]; const preview = $("#imagePreview"); if (!preview) return; if (!file) { preview.innerHTML = "<span>Image preview appears here</span>"; return; } const reader = new FileReader(); reader.onload = () => { preview.innerHTML = `<img src="${reader.result}" alt="Selected crop observation preview">`; }; reader.readAsDataURL(file); });
    $("#observationForm")?.addEventListener("submit", (event) => { event.preventDefault(); const field = $("#observationField")?.value; const crop = $("#observationCrop")?.value.trim(); const notes = $("#observationNotes")?.value.trim(); const file = $("#observationImage")?.files?.[0]; const result = $("#observationResult"); if (!field || !CROP_RULES[crop] || !notes) { if (result) { result.classList.remove("hidden"); result.textContent = "Select a field, choose a crop from the catalog, and add a short observation note."; } return; } const observation = { id: `obs-${Date.now()}`, field, crop, notes, imageName: file?.name || null, timestamp: nowIso(), status: "prepared_for_edge_ai" }; state.workspace.observations.unshift(observation); addEvent("observation", "Edge AI observation prepared", `${crop} observation recorded for ${field}${file ? ` with image ${file.name}` : " without an image"}. Vision analysis is not connected.`); saveWorkspace(); if (result) { result.classList.remove("hidden"); result.textContent = "Observation prepared. Edge AI integration ready; vision analysis is not connected and no diagnosis was made."; } $("#observationNotes").value = ""; renderAll(); toast("Observation prepared for the future Edge AI boundary."); });
    $$(".filter-btn").forEach((button) => button.addEventListener("click", () => { $$(".filter-btn").forEach((item) => item.classList.remove("active")); button.classList.add("active"); state.alertFilter = button.dataset.alertFilter; renderAlerts(); })); $("#refreshAlertsBtn")?.addEventListener("click", () => { renderAll(); toast("Crop-aware assessment refreshed from local illustrative input."); }); $("#alertsList")?.addEventListener("click", (event) => { const button = event.target.closest(".resolve-alert"); if (!button) return; const assessment = buildAssessment(state.workspace.profile); const alert = assessmentAlerts(state.workspace.profile, assessment).find((item) => item.id === button.dataset.alertId); if (!alert) return; state.workspace.alerts.push({ ...alert, status: "resolved", resolvedAt: nowIso() }); addEvent("action", "Risk alert marked reviewed", `${alert.title} was marked reviewed for ${alert.field}.`); saveWorkspace(); renderAll(); toast("Alert reviewed and farmer action added to history."); });
    $("#historyFilter")?.addEventListener("change", (event) => { state.historyFilter = event.target.value; renderHistory(); }); $("#clearDemoHistoryBtn")?.addEventListener("click", () => { state.workspace.events = []; saveWorkspace(); renderHistory(); toast("Event history cleared for this local workspace."); }); $("#addTraceEventBtn")?.addEventListener("click", () => { if (!state.workspace.profile) { toast("Set up a farmer profile before adding a field action."); return; } state.workspace.traceEvents = [...(state.workspace.traceEvents || []), { id: `trace-${Date.now()}`, title: "Farmer action recorded", detail: "Field observation or recovery action", status: "done" }]; addEvent("action", "Farmer action recorded", "A recovery-loop action was added to the local field record."); saveWorkspace(); renderTraceability(); renderHistory(); toast("Farmer action added to the recovery record."); });
    $("#saveSettingsBtn")?.addEventListener("click", () => { state.workspace.settings = { tempThreshold: Number($("#tempThreshold")?.value || 32), humidityThreshold: Number($("#humidityThreshold")?.value || 75), localNotifications: Boolean($("#localNotifications")?.checked) }; localStorage.setItem(SETTINGS_KEY, JSON.stringify(state.workspace.settings)); saveWorkspace(); addEvent("system", "Workspace preferences saved", "Local thresholds were updated in this browser."); toast("Preferences saved locally."); }); $("#resetWorkspaceBtn")?.addEventListener("click", () => { if (!window.confirm("Reset this browser's BhoomiNOVA field data?")) return; localStorage.removeItem(storageKey()); state.workspace = EMPTY_WORKSPACE(); renderAll(); toast("Local field workspace reset."); }); window.addEventListener("resize", drawAllCharts);
  }
  if (firebaseReady) firebase.auth().onAuthStateChanged(async (user) => { if (user) { state.session = { mode: "firebase", uid: user.uid, phone: user.phoneNumber || "" }; loadWorkspace(); const remote = await loadFirebaseProfile(user); if (remote) { state.workspace.profile = remote; saveWorkspace(); } renderAll(); if (!state.workspace.profile) openProfileForm(); } else if (state.session?.mode !== "demo") { state.session = null; state.workspace = EMPTY_WORKSPACE(); renderAll(); } });
  bindEvents(); loadWorkspace(); renderAll();
})();
